const list = [
    {
      id: 1,
      title: "Open-hills",
      author: "by Diego",
      price: 25000,
      img: "./Images/sandal-diego.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "chunky boots",
      author: "by Maple Press",
      price: 40000,
      img: "./Images/shoe1.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Casual-black-sandal",
      author: "by Om ",
      price: 20000,
      img: "./Images/Casual-black-sandal.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Kristina-sandals",
      author: "by Kristina",
      price: 25000,
      img: "./Images/Kristina-sandals.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Anna-bridal",
      author: "by Anna",
      price: 35000,
      img: "./Images/Anna.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "Men-sandal",
      author: "by Omal",
      price: 35000,
      img: "./Images/men-sandal.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Pink Casual Sandal ",
      author: "by Gucci",
      price: 25000,
      img: "./Images/pink-casual.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Sport ladies shoe",
      author: "by Wonder",
      price: 28000,
      img: "./Images/shoe2.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "White Casual Sandal ",
      author: "by Concorde",
      price: 80000,
      img: "./Images/shoe3.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "White junky boots",
      author: "by Maple Press" ,
      price: 86000,
      img: "./Images/white-shoe.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Casual relaxed sandal",
      author: "by Rebecca Smith ",
      price: 15000,
      img: "./Images/white-casual-sandal.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Casual relaxed sandal",
      author: "by Rebecca Smith ",
      price: 15000,
      img: "./Images/white-casual-sandal.jpg",
      amount: 1,
    },
  ];
  
  export default list;